packages:
  - payload-utils
  - payload-blog
  - payload-multi-tenant
  - payload-nested-docs
  - payload-pms
  - payload-rbac
  - payload-tenant-theming
  - payload-lexical-ext
  - payload-sync
  - payload-auditlog

autoInstallPeers: false
